name: MyStore
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_auth: ^4.17.9
  firebase_core: ^2.27.1
  cloud_firestore: ^4.15.9
  provider:
  google_fonts:
  flutter_svg:
  loading_animation_widget:
  flutter_native_splash: 
  animate_do:
  class_to_map:
  awesome_dialog:


flutter_native_splash:
  android: true
  ios: true
  web: false

  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  change_app_package_name: ^1.1.0
  flutter_launcher_icons:
  

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/logo.png"

flutter:
  assets:
    - assets/images/
    - assets/
  fonts:
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Black.ttf
  uses-material-design: true
